# Generated by Django 4.2.4 on 2023-10-12 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Loginapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentregister",
            old_name="login_id",
            new_name="log_id",
        ),
    ]
