# Generated by Django 4.2.4 on 2023-10-12 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Loginapp", "0002_rename_login_id_studentregister_log_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="login",
            name="email",
        ),
    ]
